export const GET_CATEGORIES = 'cat/GET_CATEGORIES'
export const GET_CATEGORIES_SUCCESS = 'cat/GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAIL = 'cat/GET_CATEGORIES_FAIL'
export const SET_ACTIVE_CATEGORY = 'cat/SET_ACTIVE_CATEGORY'