export const GET_CATEGORIES = 'cat/GET_CATEGORIES'
export const GET_CATEGORIES_SUCCESS = 'cat/GET_CATEGORIES_SUCCESS'
export const GET_CATEGORIES_FAIL = 'cat/GET_CATEGORIES_FAIL'
export const SET_ACTIVE_CATEGORY = 'cat/SET_ACTIVE_CATEGORY'
export const CLEAR_CATEGORIES_STORE = 'cat/CLEAR_CATEGORIES_STORE'

export const ADD_CATEGORY = 'cat/ADD_CATEGORY'
export const ADD_CATEGORY_SUCCESS = 'cat/ADD_CATEGORY_SUCCESS'
export const ADD_CATEGORY_FAIL = 'cat/ADD_CATEGORY_FAIL'

export const DELETE_CATEGORY = 'cat/DELETE_CATEGORY'
export const DELETE_CATEGORY_SUCCESS = 'cat/DELETE_CATEGORY_SUCCESS'
export const DELETE_CATEGORY_FAIL = 'cat/DELETE_CATEGORY_FAIL'

export const UPDATE_CATEGORY = 'cat/UPDATE_CATEGORY'
export const UPDATE_CATEGORY_SUCCESS = 'cat/UPDATE_CATEGORY_SUCCESS'
export const UPDATE_CATEGORY_FAIL = 'cat/UPDATE_CATEGORY_FAIL'

export const TOGGLE_LOADING_CATEGORY = 'cat/TOGGLE_LOADING_CATEGORY'